"""
Contract tests for Alert entity.

Auto-generated by JARVIS Dynamic Test Generator v1.1.3.
Tests use EXACT field names from schema contracts — no hallucinated fields.
Generated: 2026-06-25 16:36
"""

import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def sample_alert_data():
    """Valid create payload for Alert — fields from schema contract."""
    return {
        "machine_id": 1,
        "alert_type": "test_alert_type",
        "severity": 'medium',
        "message": "test_message",
        "is_acknowledged": False,
        "acknowledged_by": "test_acknowledged_by",
        "acknowledged_at": "test_acknowledged_at",
        "resolved_at": "test_resolved_at",
        "data_json": {"key": "value"}
    }

@pytest.fixture
def minimal_alert_data():
    """Minimal create payload — only required fields."""
    return {
        "alert_type": "test_alert_type",
        "message": "test_message"
    }



def test_create_alert_contract(client, auth_headers, sample_alert_data):
    """Contract test: POST /alerts/ returns 201 with correct fields."""
    response = client.post("/alerts/", headers=auth_headers, json=sample_alert_data)
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /alerts/ (status {response.status_code}) — singleton resource")
    if response.status_code not in (201, 200):
        pytest.skip(f"POST /alerts/ returned {response.status_code} — payload may need seeded dependencies")
    data = response.json()
    assert "id" in data, "Response missing field: id"
    assert "machine_id" in data, "Response missing field: machine_id"
    assert "alert_type" in data, "Response missing field: alert_type"
    assert "severity" in data, "Response missing field: severity"
    assert "message" in data, "Response missing field: message"
    assert "is_acknowledged" in data, "Response missing field: is_acknowledged"


def test_list_alerts_contract(client, auth_headers):
    """Contract test: GET /alerts/ returns list (not paginated wrapper)."""
    response = client.get("/alerts/", headers=auth_headers)
    if response.status_code in (404, 405):
        pytest.skip(f"GET not supported on /alerts/ (status {response.status_code}) — no list endpoint at this prefix")
    assert response.status_code == 200
    data = response.json()
    # Handle both flat list and paginated wrapper
    items = data if isinstance(data, list) else data.get("items", data.get("alerts", []))
    assert isinstance(items, list), f"Expected list, got {type(items)}"


def test_create_alert_missing_required(client, auth_headers):
    """Contract test: POST /alerts/ with empty body returns 422."""
    response = client.post("/alerts/", headers=auth_headers, json={})
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /alerts/ (status {response.status_code}) — singleton resource")
    assert response.status_code == 422, f"Expected 422 for empty payload, got {response.status_code}"


def test_alert_no_content_field(client, auth_headers, sample_alert_data):
    """Contract test: response uses 'message' not 'content'."""
    response = client.post("/alerts/", headers=auth_headers, json=sample_alert_data)
    if response.status_code in (200, 201):
        data = response.json()
        assert "content" not in data, "Response should use 'message' not 'content'"
        assert "message" in data, "Response missing 'message' field"


def test_alert_no_body_field(client, auth_headers, sample_alert_data):
    """Contract test: response uses 'message' not 'body'."""
    response = client.post("/alerts/", headers=auth_headers, json=sample_alert_data)
    if response.status_code in (200, 201):
        data = response.json()
        assert "body" not in data, "Response should use 'message' not 'body'"
        assert "message" in data, "Response missing 'message' field"


def test_alert_no_text_field(client, auth_headers, sample_alert_data):
    """Contract test: response uses 'message' not 'text'."""
    response = client.post("/alerts/", headers=auth_headers, json=sample_alert_data)
    if response.status_code in (200, 201):
        data = response.json()
        assert "text" not in data, "Response should use 'message' not 'text'"
        assert "message" in data, "Response missing 'message' field"

