"""
Contract tests for EmailSendLog entity.

Auto-generated by JARVIS Dynamic Test Generator v1.1.3.
Tests use EXACT field names from schema contracts — no hallucinated fields.
Generated: 2026-06-25 16:36
"""

import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def sample_email_send_log_data():
    """Valid create payload for EmailSendLog — fields from schema contract."""
    return {
        "lead_id": 1,
        "sequence_id": 1,
        "step_number": 0,
        "subject": "test_subject",
        "status": "test_status",
        "sent_at": "test_sent_at",
        "opened_at": "test_opened_at",
        "clicked_at": "test_clicked_at"
    }

@pytest.fixture
def minimal_email_send_log_data():
    """Minimal create payload — only required fields."""
    return {
        "lead_id": 1,
        "sequence_id": 1,
        "step_number": "test_step_number",
        "subject": "test_subject",
        "status": "test_status",
        "sent_at": "test_sent_at",
        "opened_at": "test_opened_at",
        "clicked_at": "test_clicked_at"
    }



def test_create_email_send_log_contract(client, auth_headers, sample_email_send_log_data):
    """Contract test: POST /email_send_logs/ returns 201 with correct fields."""
    response = client.post("/email_send_logs/", headers=auth_headers, json=sample_email_send_log_data)
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /email_send_logs/ (status {response.status_code}) — singleton resource")
    if response.status_code not in (201, 200):
        pytest.skip(f"POST /email_send_logs/ returned {response.status_code} — payload may need seeded dependencies")
    data = response.json()
    assert "id" in data, "Response missing field: id"
    assert "lead_id" in data, "Response missing field: lead_id"
    assert "sequence_id" in data, "Response missing field: sequence_id"
    assert "step_number" in data, "Response missing field: step_number"
    assert "subject" in data, "Response missing field: subject"
    assert "status" in data, "Response missing field: status"


def test_list_email_send_logs_contract(client, auth_headers):
    """Contract test: GET /email_send_logs/ returns list (not paginated wrapper)."""
    response = client.get("/email_send_logs/", headers=auth_headers)
    if response.status_code in (404, 405):
        pytest.skip(f"GET not supported on /email_send_logs/ (status {response.status_code}) — no list endpoint at this prefix")
    assert response.status_code == 200
    data = response.json()
    # Handle both flat list and paginated wrapper
    items = data if isinstance(data, list) else data.get("items", data.get("email_send_logs", []))
    assert isinstance(items, list), f"Expected list, got {type(items)}"

