"""
Contract tests for MarketingTemplate entity.

Auto-generated by JARVIS Dynamic Test Generator v1.1.3.
Tests use EXACT field names from schema contracts — no hallucinated fields.
Generated: 2026-06-25 16:36
"""

import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def sample_marketing_template_data():
    """Valid create payload for MarketingTemplate — fields from schema contract."""
    return {
        "name": "test_name",
        "category": "test_category",
        "template_type": "test_template_type",
        "content_html": "test_content_html",
        "thumbnail_url": "https://example.com/logo.png",
        "is_active": True
    }

@pytest.fixture
def minimal_marketing_template_data():
    """Minimal create payload — only required fields."""
    return {
        "name": "test_name",
        "category": "test_category"
    }



def test_create_marketing_template_contract(client, auth_headers, sample_marketing_template_data):
    """Contract test: POST /marketing_templates/ returns 201 with correct fields."""
    response = client.post("/marketing_templates/", headers=auth_headers, json=sample_marketing_template_data)
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /marketing_templates/ (status {response.status_code}) — singleton resource")
    if response.status_code not in (201, 200):
        pytest.skip(f"POST /marketing_templates/ returned {response.status_code} — payload may need seeded dependencies")
    data = response.json()
    assert "id" in data, "Response missing field: id"
    assert "name" in data, "Response missing field: name"
    assert "category" in data, "Response missing field: category"
    assert "template_type" in data, "Response missing field: template_type"
    assert "content_html" in data, "Response missing field: content_html"
    assert "thumbnail_url" in data, "Response missing field: thumbnail_url"


def test_list_marketing_templates_contract(client, auth_headers):
    """Contract test: GET /marketing_templates/ returns list (not paginated wrapper)."""
    response = client.get("/marketing_templates/", headers=auth_headers)
    if response.status_code in (404, 405):
        pytest.skip(f"GET not supported on /marketing_templates/ (status {response.status_code}) — no list endpoint at this prefix")
    assert response.status_code == 200
    data = response.json()
    # Handle both flat list and paginated wrapper
    items = data if isinstance(data, list) else data.get("items", data.get("marketing_templates", []))
    assert isinstance(items, list), f"Expected list, got {type(items)}"


def test_create_marketing_template_missing_required(client, auth_headers):
    """Contract test: POST /marketing_templates/ with empty body returns 422."""
    response = client.post("/marketing_templates/", headers=auth_headers, json={})
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /marketing_templates/ (status {response.status_code}) — singleton resource")
    assert response.status_code == 422, f"Expected 422 for empty payload, got {response.status_code}"

