"""
Contract tests for DailyReport entity.

Auto-generated by JARVIS Dynamic Test Generator v1.1.3.
Tests use EXACT field names from schema contracts — no hallucinated fields.
Generated: 2026-06-25 16:36
"""

import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def sample_daily_report_data():
    """Valid create payload for DailyReport — fields from schema contract."""
    return {
        "machine_id": 1,
        "report_date": "2026-01-15",
        "total_transactions": 0,
        "total_revenue": "test_total_revenue",
        "card_revenue": "test_card_revenue",
        "cash_revenue": "test_cash_revenue",
        "items_sold": 0,
        "avg_transaction": "test_avg_transaction",
        "uptime_hours": "test_uptime_hours",
        "alerts_count": 0
    }

@pytest.fixture
def minimal_daily_report_data():
    """Minimal create payload — only required fields."""
    return {
        "machine_id": 1
    }



def test_create_daily_report_contract(client, auth_headers, sample_daily_report_data):
    """Contract test: POST /daily_reports/ returns 201 with correct fields."""
    response = client.post("/daily_reports/", headers=auth_headers, json=sample_daily_report_data)
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /daily_reports/ (status {response.status_code}) — singleton resource")
    if response.status_code not in (201, 200):
        pytest.skip(f"POST /daily_reports/ returned {response.status_code} — payload may need seeded dependencies")
    data = response.json()
    assert "id" in data, "Response missing field: id"
    assert "machine_id" in data, "Response missing field: machine_id"
    assert "report_date" in data, "Response missing field: report_date"
    assert "total_transactions" in data, "Response missing field: total_transactions"
    assert "total_revenue" in data, "Response missing field: total_revenue"
    assert "card_revenue" in data, "Response missing field: card_revenue"


def test_list_daily_reports_contract(client, auth_headers):
    """Contract test: GET /daily_reports/ returns list (not paginated wrapper)."""
    response = client.get("/daily_reports/", headers=auth_headers)
    if response.status_code in (404, 405):
        pytest.skip(f"GET not supported on /daily_reports/ (status {response.status_code}) — no list endpoint at this prefix")
    assert response.status_code == 200
    data = response.json()
    # Handle both flat list and paginated wrapper
    items = data if isinstance(data, list) else data.get("items", data.get("daily_reports", []))
    assert isinstance(items, list), f"Expected list, got {type(items)}"


def test_create_daily_report_missing_required(client, auth_headers):
    """Contract test: POST /daily_reports/ with empty body returns 422."""
    response = client.post("/daily_reports/", headers=auth_headers, json={})
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /daily_reports/ (status {response.status_code}) — singleton resource")
    assert response.status_code == 422, f"Expected 422 for empty payload, got {response.status_code}"

