"""
Contract tests for OperatorWebsite entity.

Auto-generated by JARVIS Dynamic Test Generator v1.1.3.
Tests use EXACT field names from schema contracts — no hallucinated fields.
Generated: 2026-06-25 16:36
"""

import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def sample_operator_website_data():
    """Valid create payload for OperatorWebsite — fields from schema contract."""
    return {
        "operator_id": 1,
        "domain": "test_domain",
        "subdomain": "test_subdomain",
        "company_name": "test_company_name",
        "tagline": "test_tagline",
        "logo_url": "https://example.com/logo.png",
        "primary_color": "test_primary_color",
        "phone": "806-555-1234",
        "email": "test@example.com",
        "about_text": "test_about_text",
        "services_json": {"key": "value"},
        "chatbot_enabled": False,
        "chatbot_greeting": "test_chatbot_greeting",
        "is_published": False,
        "template_id": 1
    }

@pytest.fixture
def minimal_operator_website_data():
    """Minimal create payload — only required fields."""
    return {
        "company_name": "test_company_name"
    }



def test_create_operator_website_contract(client, auth_headers, sample_operator_website_data):
    """Contract test: POST /operator_websites/ returns 201 with correct fields."""
    response = client.post("/operator_websites/", headers=auth_headers, json=sample_operator_website_data)
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /operator_websites/ (status {response.status_code}) — singleton resource")
    if response.status_code not in (201, 200):
        pytest.skip(f"POST /operator_websites/ returned {response.status_code} — payload may need seeded dependencies")
    data = response.json()
    assert "id" in data, "Response missing field: id"
    assert "operator_id" in data, "Response missing field: operator_id"
    assert "domain" in data, "Response missing field: domain"
    assert "subdomain" in data, "Response missing field: subdomain"
    assert "company_name" in data, "Response missing field: company_name"
    assert "tagline" in data, "Response missing field: tagline"


def test_list_operator_websites_contract(client, auth_headers):
    """Contract test: GET /operator_websites/ returns list (not paginated wrapper)."""
    response = client.get("/operator_websites/", headers=auth_headers)
    if response.status_code in (404, 405):
        pytest.skip(f"GET not supported on /operator_websites/ (status {response.status_code}) — no list endpoint at this prefix")
    assert response.status_code == 200
    data = response.json()
    # Handle both flat list and paginated wrapper
    items = data if isinstance(data, list) else data.get("items", data.get("operator_websites", []))
    assert isinstance(items, list), f"Expected list, got {type(items)}"


def test_create_operator_website_missing_required(client, auth_headers):
    """Contract test: POST /operator_websites/ with empty body returns 422."""
    response = client.post("/operator_websites/", headers=auth_headers, json={})
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /operator_websites/ (status {response.status_code}) — singleton resource")
    assert response.status_code == 422, f"Expected 422 for empty payload, got {response.status_code}"

