"""
Contract tests for Operator entity.

Auto-generated by JARVIS Dynamic Test Generator v1.1.3.
Tests use EXACT field names from schema contracts — no hallucinated fields.
Generated: 2026-06-25 16:36
"""

import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def sample_operator_data():
    """Valid create payload for Operator — fields from schema contract."""
    return {
        "name": "test_name",
        "contact_name": "test_contact_name",
        "contact_email": "test@example.com",
        "contact_phone": "806-555-1234",
        "address": "test_address",
        "city": "test_city",
        "state": "test_state",
        "zip_code": "test_zip_code",
        "machine_count": 0,
        "monthly_volume": "test_monthly_volume",
        "processing_rate": 3.0,
        "software_rate": 9.0,
        "is_active": True
    }

@pytest.fixture
def minimal_operator_data():
    """Minimal create payload — only required fields."""
    return {
        "name": "test_name"
    }



def test_create_operator_contract(client, auth_headers, sample_operator_data):
    """Contract test: POST /operators/ returns 201 with correct fields."""
    response = client.post("/operators/", headers=auth_headers, json=sample_operator_data)
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /operators/ (status {response.status_code}) — singleton resource")
    if response.status_code not in (201, 200):
        pytest.skip(f"POST /operators/ returned {response.status_code} — payload may need seeded dependencies")
    data = response.json()
    assert "id" in data, "Response missing field: id"
    assert "name" in data, "Response missing field: name"
    assert "contact_name" in data, "Response missing field: contact_name"
    assert "contact_email" in data, "Response missing field: contact_email"
    assert "contact_phone" in data, "Response missing field: contact_phone"
    assert "address" in data, "Response missing field: address"


def test_list_operators_contract(client, auth_headers):
    """Contract test: GET /operators/ returns list (not paginated wrapper)."""
    response = client.get("/operators/", headers=auth_headers)
    if response.status_code in (404, 405):
        pytest.skip(f"GET not supported on /operators/ (status {response.status_code}) — no list endpoint at this prefix")
    assert response.status_code == 200
    data = response.json()
    # Handle both flat list and paginated wrapper
    items = data if isinstance(data, list) else data.get("items", data.get("operators", []))
    assert isinstance(items, list), f"Expected list, got {type(items)}"


def test_create_operator_missing_required(client, auth_headers):
    """Contract test: POST /operators/ with empty body returns 422."""
    response = client.post("/operators/", headers=auth_headers, json={})
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /operators/ (status {response.status_code}) — singleton resource")
    assert response.status_code == 422, f"Expected 422 for empty payload, got {response.status_code}"

