"""
Contract tests for Route entity.

Auto-generated by JARVIS Dynamic Test Generator v1.1.3.
Tests use EXACT field names from schema contracts — no hallucinated fields.
Generated: 2026-06-25 16:36
"""

import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def sample_route_data():
    """Valid create payload for Route — fields from schema contract."""
    return {
        "operator_id": 1,
        "driver_id": 1,
        "name": "test_name",
        "status": 'planned',
        "scheduled_date": "2026-01-15",
        "started_at": "test_started_at",
        "completed_at": "test_completed_at",
        "machine_ids_json": 1,
        "optimized_order_json": {"key": "value"},
        "total_distance_miles": "test_total_distance_miles",
        "notes": "test_notes"
    }

@pytest.fixture
def minimal_route_data():
    """Minimal create payload — only required fields."""
    return {
        "operator_id": 1,
        "name": "test_name"
    }



def test_create_route_contract(client, auth_headers, sample_route_data):
    """Contract test: POST /routes/ returns 201 with correct fields."""
    response = client.post("/routes/", headers=auth_headers, json=sample_route_data)
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /routes/ (status {response.status_code}) — singleton resource")
    if response.status_code not in (201, 200):
        pytest.skip(f"POST /routes/ returned {response.status_code} — payload may need seeded dependencies")
    data = response.json()
    assert "id" in data, "Response missing field: id"
    assert "operator_id" in data, "Response missing field: operator_id"
    assert "driver_id" in data, "Response missing field: driver_id"
    assert "name" in data, "Response missing field: name"
    assert "status" in data, "Response missing field: status"
    assert "scheduled_date" in data, "Response missing field: scheduled_date"


def test_list_routes_contract(client, auth_headers):
    """Contract test: GET /routes/ returns list (not paginated wrapper)."""
    response = client.get("/routes/", headers=auth_headers)
    if response.status_code in (404, 405):
        pytest.skip(f"GET not supported on /routes/ (status {response.status_code}) — no list endpoint at this prefix")
    assert response.status_code == 200
    data = response.json()
    # Handle both flat list and paginated wrapper
    items = data if isinstance(data, list) else data.get("items", data.get("routes", []))
    assert isinstance(items, list), f"Expected list, got {type(items)}"


def test_create_route_missing_required(client, auth_headers):
    """Contract test: POST /routes/ with empty body returns 422."""
    response = client.post("/routes/", headers=auth_headers, json={})
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /routes/ (status {response.status_code}) — singleton resource")
    assert response.status_code == 422, f"Expected 422 for empty payload, got {response.status_code}"

