"""
Contract tests for Lead entity.

Auto-generated by JARVIS Dynamic Test Generator v1.1.3.
Tests use EXACT field names from schema contracts — no hallucinated fields.
Generated: 2026-06-25 16:36
"""

import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def sample_lead_data():
    """Valid create payload for Lead — fields from schema contract."""
    return {
        "operator_id": 1,
        "business_name": "test_business_name",
        "contact_name": "test_contact_name",
        "contact_email": "test@example.com",
        "contact_phone": "806-555-1234",
        "address": "test_address",
        "city": "test_city",
        "state": "test_state",
        "zip_code": "test_zip_code",
        "latitude": "test_latitude",
        "longitude": "test_longitude",
        "business_type": "test_business_type",
        "status": "test_status",
        "source": "test_source",
        "notes": "test_notes",
        "next_follow_up_at": "test_next_follow_up_at",
        "mockup_image_url": "https://example.com/logo.png"
    }

@pytest.fixture
def minimal_lead_data():
    """Minimal create payload — only required fields."""
    return {
        "business_name": "test_business_name"
    }



def test_create_lead_contract(client, auth_headers, sample_lead_data):
    """Contract test: POST /leads/ returns 201 with correct fields."""
    response = client.post("/leads/", headers=auth_headers, json=sample_lead_data)
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /leads/ (status {response.status_code}) — singleton resource")
    if response.status_code not in (201, 200):
        pytest.skip(f"POST /leads/ returned {response.status_code} — payload may need seeded dependencies")
    data = response.json()
    assert "id" in data, "Response missing field: id"
    assert "operator_id" in data, "Response missing field: operator_id"
    assert "business_name" in data, "Response missing field: business_name"
    assert "contact_name" in data, "Response missing field: contact_name"
    assert "contact_email" in data, "Response missing field: contact_email"
    assert "contact_phone" in data, "Response missing field: contact_phone"


def test_list_leads_contract(client, auth_headers):
    """Contract test: GET /leads/ returns list (not paginated wrapper)."""
    response = client.get("/leads/", headers=auth_headers)
    if response.status_code in (404, 405):
        pytest.skip(f"GET not supported on /leads/ (status {response.status_code}) — no list endpoint at this prefix")
    assert response.status_code == 200
    data = response.json()
    # Handle both flat list and paginated wrapper
    items = data if isinstance(data, list) else data.get("items", data.get("leads", []))
    assert isinstance(items, list), f"Expected list, got {type(items)}"


def test_create_lead_missing_required(client, auth_headers):
    """Contract test: POST /leads/ with empty body returns 422."""
    response = client.post("/leads/", headers=auth_headers, json={})
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /leads/ (status {response.status_code}) — singleton resource")
    assert response.status_code == 422, f"Expected 422 for empty payload, got {response.status_code}"


def test_lead_no_comment_field(client, auth_headers, sample_lead_data):
    """Contract test: response uses 'notes' not 'comment'."""
    response = client.post("/leads/", headers=auth_headers, json=sample_lead_data)
    if response.status_code in (200, 201):
        data = response.json()
        assert "comment" not in data, "Response should use 'notes' not 'comment'"
        assert "notes" in data, "Response missing 'notes' field"

