"""
Contract tests for Inventory entity.

Auto-generated by JARVIS Dynamic Test Generator v1.1.3.
Tests use EXACT field names from schema contracts — no hallucinated fields.
Generated: 2026-06-25 16:36
"""

import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def sample_inventory_data():
    """Valid create payload for Inventory — fields from schema contract."""
    return {
        "machine_id": 1,
        "product_id": 1,
        "slot_number": "test_slot_number",
        "current_qty": 0,
        "max_qty": "test_max_qty",
        "last_restocked_at": "test_last_restocked_at"
    }

@pytest.fixture
def minimal_inventory_data():
    """Minimal create payload — only required fields."""
    return {
        "machine_id": 1,
        "product_id": 1,
        "slot_number": "test_slot_number",
        "current_qty": "test_current_qty",
        "max_qty": "test_max_qty",
        "last_restocked_at": "test_last_restocked_at"
    }



def test_create_inventory_contract(client, auth_headers, sample_inventory_data):
    """Contract test: POST /inventory/ returns 201 with correct fields."""
    response = client.post("/inventory/", headers=auth_headers, json=sample_inventory_data)
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /inventory/ (status {response.status_code}) — singleton resource")
    if response.status_code not in (201, 200):
        pytest.skip(f"POST /inventory/ returned {response.status_code} — payload may need seeded dependencies")
    data = response.json()
    assert "id" in data, "Response missing field: id"
    assert "machine_id" in data, "Response missing field: machine_id"
    assert "product_id" in data, "Response missing field: product_id"
    assert "slot_number" in data, "Response missing field: slot_number"
    assert "current_qty" in data, "Response missing field: current_qty"
    assert "max_qty" in data, "Response missing field: max_qty"


def test_list_inventorys_contract(client, auth_headers):
    """Contract test: GET /inventory/ returns list (not paginated wrapper)."""
    response = client.get("/inventory/", headers=auth_headers)
    if response.status_code in (404, 405):
        pytest.skip(f"GET not supported on /inventory/ (status {response.status_code}) — no list endpoint at this prefix")
    assert response.status_code == 200
    data = response.json()
    # Handle both flat list and paginated wrapper
    items = data if isinstance(data, list) else data.get("items", data.get("inventorys", []))
    assert isinstance(items, list), f"Expected list, got {type(items)}"

