"""
Contract tests for Transaction entity.

Auto-generated by JARVIS Dynamic Test Generator v1.1.3.
Tests use EXACT field names from schema contracts — no hallucinated fields.
Generated: 2026-06-25 16:36
"""

import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def sample_transaction_data():
    """Valid create payload for Transaction — fields from schema contract."""
    return {
        "machine_id": 1,
        "product_id": 1,
        "amount": 50000.00,
        "payment_method": "test_payment_method",
        "payment_status": "test_payment_status",
        "payment_ref": "test_payment_ref",
        "card_brand": "test_card_brand",
        "card_last_four": "test_card_last_four",
        "terminal_id": 1,
        "slot_number": "test_slot_number"
    }

@pytest.fixture
def minimal_transaction_data():
    """Minimal create payload — only required fields."""
    return {
        "machine_id": 1,
        "amount": 50000.00
    }



def test_create_transaction_contract(client, auth_headers, sample_transaction_data):
    """Contract test: POST /transactions/ returns 201 with correct fields."""
    response = client.post("/transactions/", headers=auth_headers, json=sample_transaction_data)
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /transactions/ (status {response.status_code}) — singleton resource")
    if response.status_code not in (201, 200):
        pytest.skip(f"POST /transactions/ returned {response.status_code} — payload may need seeded dependencies")
    data = response.json()
    assert "id" in data, "Response missing field: id"
    assert "machine_id" in data, "Response missing field: machine_id"
    assert "product_id" in data, "Response missing field: product_id"
    assert "amount" in data, "Response missing field: amount"
    assert "payment_method" in data, "Response missing field: payment_method"
    assert "payment_status" in data, "Response missing field: payment_status"


def test_list_transactions_contract(client, auth_headers):
    """Contract test: GET /transactions/ returns list (not paginated wrapper)."""
    response = client.get("/transactions/", headers=auth_headers)
    if response.status_code in (404, 405):
        pytest.skip(f"GET not supported on /transactions/ (status {response.status_code}) — no list endpoint at this prefix")
    assert response.status_code == 200
    data = response.json()
    # Handle both flat list and paginated wrapper
    items = data if isinstance(data, list) else data.get("items", data.get("transactions", []))
    assert isinstance(items, list), f"Expected list, got {type(items)}"


def test_create_transaction_missing_required(client, auth_headers):
    """Contract test: POST /transactions/ with empty body returns 422."""
    response = client.post("/transactions/", headers=auth_headers, json={})
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /transactions/ (status {response.status_code}) — singleton resource")
    assert response.status_code == 422, f"Expected 422 for empty payload, got {response.status_code}"

