"""
Contract tests for Analytics entity.

Auto-generated by JARVIS Dynamic Test Generator v1.1.3.
Tests use EXACT field names from schema contracts — no hallucinated fields.
Generated: 2026-06-25 16:36
"""

import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def sample_analytics_data():
    """Valid create payload for Analytics — fields from schema contract."""
    return {
        "title": "test_title",
        "description": "test_description",
        "status": 'active'
    }

@pytest.fixture
def minimal_analytics_data():
    """Minimal create payload — only required fields."""
    return {
        "title": "test_title"
    }



def test_create_analytics_contract(client, auth_headers, sample_analytics_data):
    """Contract test: POST /analytics/ returns 201 with correct fields."""
    response = client.post("/analytics/", headers=auth_headers, json=sample_analytics_data)
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /analytics/ (status {response.status_code}) — singleton resource")
    if response.status_code not in (201, 200):
        pytest.skip(f"POST /analytics/ returned {response.status_code} — payload may need seeded dependencies")
    data = response.json()
    assert "id" in data, "Response missing field: id"
    assert "title" in data, "Response missing field: title"
    assert "description" in data, "Response missing field: description"
    assert "status" in data, "Response missing field: status"
    assert "created_at" in data, "Response missing field: created_at"


def test_list_analyticss_contract(client, auth_headers):
    """Contract test: GET /analytics/ returns list (not paginated wrapper)."""
    response = client.get("/analytics/", headers=auth_headers)
    if response.status_code in (404, 405):
        pytest.skip(f"GET not supported on /analytics/ (status {response.status_code}) — no list endpoint at this prefix")
    assert response.status_code == 200
    data = response.json()
    # Handle both flat list and paginated wrapper
    items = data if isinstance(data, list) else data.get("items", data.get("analyticss", []))
    assert isinstance(items, list), f"Expected list, got {type(items)}"


def test_create_analytics_missing_required(client, auth_headers):
    """Contract test: POST /analytics/ with empty body returns 422."""
    response = client.post("/analytics/", headers=auth_headers, json={})
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /analytics/ (status {response.status_code}) — singleton resource")
    assert response.status_code == 422, f"Expected 422 for empty payload, got {response.status_code}"


def test_analytics_no_content_field(client, auth_headers, sample_analytics_data):
    """Contract test: response uses 'description' not 'content'."""
    response = client.post("/analytics/", headers=auth_headers, json=sample_analytics_data)
    if response.status_code in (200, 201):
        data = response.json()
        assert "content" not in data, "Response should use 'description' not 'content'"
        assert "description" in data, "Response missing 'description' field"


def test_analytics_no_body_field(client, auth_headers, sample_analytics_data):
    """Contract test: response uses 'description' not 'body'."""
    response = client.post("/analytics/", headers=auth_headers, json=sample_analytics_data)
    if response.status_code in (200, 201):
        data = response.json()
        assert "body" not in data, "Response should use 'description' not 'body'"
        assert "description" in data, "Response missing 'description' field"

