"""
Contract tests for Machine entity.

Auto-generated by JARVIS Dynamic Test Generator v1.1.3.
Tests use EXACT field names from schema contracts — no hallucinated fields.
Generated: 2026-06-25 16:36
"""

import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def sample_machine_data():
    """Valid create payload for Machine — fields from schema contract."""
    return {
        "serial_number": "test_serial_number",
        "machine_type": 'ice',
        "name": "test_name",
        "manufacturer": "test_manufacturer",
        "model": "test_model",
        "status": 'active',
        "operator_id": 1,
        "location_id": 1,
        "terminal_id": 1,
        "pi_device_id": 1,
        "sim_iccid": "test_sim_iccid",
        "firmware_version": "test_firmware_version",
        "temperature": "test_temperature",
        "is_online": False,
        "is_active": True,
        "last_service_at": "test_last_service_at",
        "last_restock_at": "test_last_restock_at",
        "last_telemetry_at": "test_last_telemetry_at",
        "installed_at": "test_installed_at",
        "edge_mode": 'im30_only',
        "connectivity_type": 'cellular'
    }

@pytest.fixture
def minimal_machine_data():
    """Minimal create payload — only required fields."""
    return {
        "serial_number": "test_serial_number"
    }



def test_create_machine_contract(client, auth_headers, sample_machine_data):
    """Contract test: POST /machines/ returns 201 with correct fields."""
    response = client.post("/machines/", headers=auth_headers, json=sample_machine_data)
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /machines/ (status {response.status_code}) — singleton resource")
    if response.status_code not in (201, 200):
        pytest.skip(f"POST /machines/ returned {response.status_code} — payload may need seeded dependencies")
    data = response.json()
    assert "id" in data, "Response missing field: id"
    assert "serial_number" in data, "Response missing field: serial_number"
    assert "machine_type" in data, "Response missing field: machine_type"
    assert "name" in data, "Response missing field: name"
    assert "manufacturer" in data, "Response missing field: manufacturer"
    assert "model" in data, "Response missing field: model"


def test_list_machines_contract(client, auth_headers):
    """Contract test: GET /machines/ returns list (not paginated wrapper)."""
    response = client.get("/machines/", headers=auth_headers)
    if response.status_code in (404, 405):
        pytest.skip(f"GET not supported on /machines/ (status {response.status_code}) — no list endpoint at this prefix")
    assert response.status_code == 200
    data = response.json()
    # Handle both flat list and paginated wrapper
    items = data if isinstance(data, list) else data.get("items", data.get("machines", []))
    assert isinstance(items, list), f"Expected list, got {type(items)}"


def test_create_machine_missing_required(client, auth_headers):
    """Contract test: POST /machines/ with empty body returns 422."""
    response = client.post("/machines/", headers=auth_headers, json={})
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /machines/ (status {response.status_code}) — singleton resource")
    assert response.status_code == 422, f"Expected 422 for empty payload, got {response.status_code}"

