"""
Contract tests for Location entity.

Auto-generated by JARVIS Dynamic Test Generator v1.1.3.
Tests use EXACT field names from schema contracts — no hallucinated fields.
Generated: 2026-06-25 16:36
"""

import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def sample_location_data():
    """Valid create payload for Location — fields from schema contract."""
    return {
        "operator_id": 1,
        "name": "test_name",
        "address": "test_address",
        "city": "test_city",
        "state": "test_state",
        "zip_code": "test_zip_code",
        "latitude": "test_latitude",
        "longitude": "test_longitude",
        "location_type": "test_location_type",
        "contact_name": "test_contact_name",
        "contact_phone": "806-555-1234",
        "notes": "test_notes",
        "is_active": True
    }

@pytest.fixture
def minimal_location_data():
    """Minimal create payload — only required fields."""
    return {
        "name": "test_name"
    }



def test_create_location_contract(client, auth_headers, sample_location_data):
    """Contract test: POST /locations/ returns 201 with correct fields."""
    response = client.post("/locations/", headers=auth_headers, json=sample_location_data)
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /locations/ (status {response.status_code}) — singleton resource")
    if response.status_code not in (201, 200):
        pytest.skip(f"POST /locations/ returned {response.status_code} — payload may need seeded dependencies")
    data = response.json()
    assert "id" in data, "Response missing field: id"
    assert "operator_id" in data, "Response missing field: operator_id"
    assert "name" in data, "Response missing field: name"
    assert "address" in data, "Response missing field: address"
    assert "city" in data, "Response missing field: city"
    assert "state" in data, "Response missing field: state"


def test_list_locations_contract(client, auth_headers):
    """Contract test: GET /locations/ returns list (not paginated wrapper)."""
    response = client.get("/locations/", headers=auth_headers)
    if response.status_code in (404, 405):
        pytest.skip(f"GET not supported on /locations/ (status {response.status_code}) — no list endpoint at this prefix")
    assert response.status_code == 200
    data = response.json()
    # Handle both flat list and paginated wrapper
    items = data if isinstance(data, list) else data.get("items", data.get("locations", []))
    assert isinstance(items, list), f"Expected list, got {type(items)}"


def test_create_location_missing_required(client, auth_headers):
    """Contract test: POST /locations/ with empty body returns 422."""
    response = client.post("/locations/", headers=auth_headers, json={})
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /locations/ (status {response.status_code}) — singleton resource")
    assert response.status_code == 422, f"Expected 422 for empty payload, got {response.status_code}"

