"""
Contract tests for User entity.

Auto-generated by JARVIS Dynamic Test Generator v1.1.3.
Tests use EXACT field names from schema contracts — no hallucinated fields.
Generated: 2026-06-25 16:36
"""

import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def sample_user_data():
    """Valid create payload for User — fields from schema contract."""
    return {
        "email": "test@example.com",
        "hashed_password": "test_hashed_password",
        "full_name": "test_full_name",
        "is_active": True
    }

@pytest.fixture
def minimal_user_data():
    """Minimal create payload — only required fields."""
    return {
        "email": "test@example.com",
        "password": "test_password"
    }



def test_create_user_contract(client, auth_headers, sample_user_data):
    """Contract test: POST /auth/ returns 201 with correct fields."""
    response = client.post("/auth/", headers=auth_headers, json=sample_user_data)
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /auth/ (status {response.status_code}) — singleton resource")
    if response.status_code not in (201, 200):
        pytest.skip(f"POST /auth/ returned {response.status_code} — payload may need seeded dependencies")
    data = response.json()
    assert "id" in data, "Response missing field: id"
    assert "email" in data, "Response missing field: email"
    assert "full_name" in data, "Response missing field: full_name"
    assert "is_active" in data, "Response missing field: is_active"
    assert "created_at" in data, "Response missing field: created_at"


def test_list_users_contract(client, auth_headers):
    """Contract test: GET /auth/ returns list (not paginated wrapper)."""
    response = client.get("/auth/", headers=auth_headers)
    if response.status_code in (404, 405):
        pytest.skip(f"GET not supported on /auth/ (status {response.status_code}) — no list endpoint at this prefix")
    assert response.status_code == 200
    data = response.json()
    # Handle both flat list and paginated wrapper
    items = data if isinstance(data, list) else data.get("items", data.get("users", []))
    assert isinstance(items, list), f"Expected list, got {type(items)}"


def test_create_user_missing_required(client, auth_headers):
    """Contract test: POST /auth/ with empty body returns 422."""
    response = client.post("/auth/", headers=auth_headers, json={})
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /auth/ (status {response.status_code}) — singleton resource")
    assert response.status_code == 422, f"Expected 422 for empty payload, got {response.status_code}"

