// Auto-generated by FMPB v2.4.4
// Hook: useCompany — TanStack Query wrappers for Company API
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import apiClient from '@/lib/api';

// Types — update these to match your backend schema
export interface CompanyItem {
  id: number;
  [key: string]: unknown;
}

export function useCompany() {
  return useQuery({
    queryKey: ['company'],
    queryFn: async () => {
      const { data } = await apiClient.get('/api/company');
      return data;
    },
  });
}

export function useCompanyDetail(id: number | null) {
  return useQuery({
    queryKey: ['company', id],
    queryFn: async () => {
      const { data } = await apiClient.get(`/api/company/${id}`);
      return data;
    },
    enabled: id !== null && id !== undefined,
  });
}

export function useCreateCompany() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (payload: Record<string, unknown>) => {
      const { data } = await apiClient.post('/api/company', payload);
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['company'] });
    },
  });
}

export function useUpdateCompany() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({ id, ...payload }: { id: number; [key: string]: unknown }) => {
      const { data } = await apiClient.put(`/api/company/${id}`, payload);
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['company'] });
    },
  });
}

export function useDeleteCompany() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (id: number) => {
      await apiClient.delete(`/api/company/${id}`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['company'] });
    },
  });
}

export default useCompany;
