// JARVIS App — API types (CONTRACT-FIRST, generated)
// Source of truth: the backend's own /openapi.json (frontend_contract.openapi.json).
// Generated by frontend_codegen.py v1.2.0 — DO NOT EDIT BY HAND.
// Nullability and optionality are EXACT, straight from the schema:
//   Optional[X]            -> field?: X | null
//   required, non-nullable -> field: X

export interface AlertCreate {
  machine_id?: number | null;
  alert_type: string;
  severity?: string | null;
  message: string;
  is_acknowledged?: boolean | null;
  acknowledged_by?: number | null;
  acknowledged_at?: string | null;
  resolved_at?: string | null;
  data_json?: string | null;
  id?: number | null;
}
export interface AlertResponse {
  machine_id?: number | null;
  alert_type: string;
  severity?: string | null;
  message: string;
  is_acknowledged?: boolean | null;
  acknowledged_by?: number | null;
  acknowledged_at?: string | null;
  resolved_at?: string | null;
  data_json?: string | null;
  id: number;
  created_at?: string | null;
}
export interface AlertUpdate {
  id?: number | null;
  machine_id?: number | null;
  alert_type?: string | null;
  severity?: string | null;
  message?: string | null;
  is_acknowledged?: boolean | null;
  acknowledged_by?: number | null;
  acknowledged_at?: string | null;
  resolved_at?: string | null;
  data_json?: string | null;
}
export interface AnalyticsCreate {
  title: string;
  description?: string | null;
  status?: string | null;
  id?: number | null;
}
export interface AnalyticsResponse {
  title: string;
  description?: string | null;
  status?: string | null;
  id: number;
  created_at?: string | null;
  updated_at?: string | null;
}
export interface AnalyticsUpdate {
  id?: number | null;
  title?: string | null;
  description?: string | null;
  status?: string | null;
}
export interface Body_login_auth_login_post {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
}
export interface Body_token_auth_token_post {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
}
export interface Body_upload_task_file_uploads_tasks__task_id__upload_post {
  file: string;
}
export interface DailyReportCreate {
  machine_id: number;
  report_date?: string | null;
  total_transactions?: number | null;
  total_revenue?: number | string | null;
  card_revenue?: number | string | null;
  cash_revenue?: number | string | null;
  items_sold?: number | null;
  avg_transaction?: number | string | null;
  uptime_hours?: number | string | null;
  alerts_count?: number | null;
  id?: number | null;
}
export interface DailyReportResponse {
  machine_id: number;
  report_date?: string | null;
  total_transactions?: number | null;
  total_revenue?: string | null;
  card_revenue?: string | null;
  cash_revenue?: string | null;
  items_sold?: number | null;
  avg_transaction?: string | null;
  uptime_hours?: string | null;
  alerts_count?: number | null;
  id: number;
  created_at?: string | null;
}
export interface DailyReportUpdate {
  id?: number | null;
  machine_id?: number | null;
  report_date?: string | null;
  total_transactions?: number | null;
  total_revenue?: number | string | null;
  card_revenue?: number | string | null;
  cash_revenue?: number | string | null;
  items_sold?: number | null;
  avg_transaction?: number | string | null;
  uptime_hours?: number | string | null;
  alerts_count?: number | null;
}
export interface EmailSendLogCreate {
  lead_id?: number | null;
  sequence_id?: number | null;
  step_number?: number | null;
  subject?: string | null;
  status: string;
  sent_at?: string | null;
  opened_at?: string | null;
  clicked_at?: string | null;
  id?: number | null;
}
export interface EmailSendLogResponse {
  lead_id?: number | null;
  sequence_id?: number | null;
  step_number?: number | null;
  subject?: string | null;
  status: string;
  sent_at?: string | null;
  opened_at?: string | null;
  clicked_at?: string | null;
  id: number;
  created_at?: string | null;
  updated_at?: string | null;
}
export interface EmailSendLogUpdate {
  id?: number | null;
  lead_id?: number | null;
  sequence_id?: number | null;
  step_number?: number | null;
  subject?: string | null;
  status?: string | null;
  sent_at?: string | null;
  opened_at?: string | null;
  clicked_at?: string | null;
}
export interface EmailSequenceCreate {
  operator_id?: number | null;
  name: string;
  trigger_status?: string | null;
  steps_json?: string | null;
  is_active?: boolean | null;
  id?: number | null;
}
export interface EmailSequenceResponse {
  operator_id?: number | null;
  name: string;
  trigger_status?: string | null;
  steps_json?: string | null;
  is_active?: boolean | null;
  id: number;
  created_at?: string | null;
  updated_at?: string | null;
}
export interface EmailSequenceUpdate {
  id?: number | null;
  operator_id?: number | null;
  name?: string | null;
  trigger_status?: string | null;
  steps_json?: string | null;
  is_active?: boolean | null;
}
export interface HTTPValidationError {
  detail?: ValidationError[];
}
export interface InventoryItemCreate {
  machine_id?: number | null;
  product_id?: number | null;
  slot_number?: number | null;
  current_qty?: number | null;
  max_qty?: number | null;
  last_restocked_at?: string | null;
  id?: number | null;
}
export interface InventoryItemResponse {
  machine_id?: number | null;
  product_id?: number | null;
  slot_number?: number | null;
  current_qty?: number | null;
  max_qty?: number | null;
  last_restocked_at?: string | null;
  id: number;
  created_at?: string | null;
  updated_at?: string | null;
}
export interface InventoryItemUpdate {
  id?: number | null;
  machine_id?: number | null;
  product_id?: number | null;
  slot_number?: number | null;
  current_qty?: number | null;
  max_qty?: number | null;
  last_restocked_at?: string | null;
}
export interface LeadCreate {
  operator_id?: number | null;
  business_name: string;
  contact_name?: string | null;
  contact_email?: string | null;
  contact_phone?: string | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  zip_code?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  business_type?: string | null;
  status: string;
  source?: string | null;
  notes?: string | null;
  next_follow_up_at?: string | null;
  mockup_image_url?: string | null;
  id?: number | null;
}
export interface LeadResponse {
  operator_id?: number | null;
  business_name: string;
  contact_name?: string | null;
  contact_email?: string | null;
  contact_phone?: string | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  zip_code?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  business_type?: string | null;
  status: string;
  source?: string | null;
  notes?: string | null;
  next_follow_up_at?: string | null;
  mockup_image_url?: string | null;
  id: number;
  created_at?: string | null;
  updated_at?: string | null;
}
export interface LeadUpdate {
  id?: number | null;
  operator_id?: number | null;
  business_name?: string | null;
  contact_name?: string | null;
  contact_email?: string | null;
  contact_phone?: string | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  zip_code?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  business_type?: string | null;
  status?: string | null;
  source?: string | null;
  notes?: string | null;
  next_follow_up_at?: string | null;
  mockup_image_url?: string | null;
}
export interface LocationCreate {
  operator_id?: number | null;
  name: string;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  zip_code?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  location_type?: string | null;
  contact_name?: string | null;
  contact_phone?: string | null;
  notes?: string | null;
  is_active?: boolean | null;
  id?: number | null;
}
export interface LocationResponse {
  operator_id?: number | null;
  name: string;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  zip_code?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  location_type?: string | null;
  contact_name?: string | null;
  contact_phone?: string | null;
  notes?: string | null;
  is_active?: boolean | null;
  id: number;
  created_at?: string | null;
  updated_at?: string | null;
}
export interface LocationUpdate {
  id?: number | null;
  operator_id?: number | null;
  name?: string | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  zip_code?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  location_type?: string | null;
  contact_name?: string | null;
  contact_phone?: string | null;
  notes?: string | null;
  is_active?: boolean | null;
}
export interface MachineCreate {
  serial_number: string;
  machine_type?: string | null;
  name?: string | null;
  manufacturer?: string | null;
  model?: string | null;
  status?: string | null;
  operator_id?: number | null;
  location_id?: number | null;
  terminal_id?: string | null;
  pi_device_id?: string | null;
  sim_iccid?: string | null;
  firmware_version?: string | null;
  temperature?: number | null;
  is_online?: boolean | null;
  is_active?: boolean | null;
  last_service_at?: string | null;
  last_restock_at?: string | null;
  last_telemetry_at?: string | null;
  installed_at?: string | null;
  edge_mode?: string | null;
  connectivity_type?: string | null;
  id?: number | null;
}
export interface MachineResponse {
  serial_number: string;
  machine_type?: string | null;
  name?: string | null;
  manufacturer?: string | null;
  model?: string | null;
  status?: string | null;
  operator_id?: number | null;
  location_id?: number | null;
  terminal_id?: string | null;
  pi_device_id?: string | null;
  sim_iccid?: string | null;
  firmware_version?: string | null;
  temperature?: number | null;
  is_online?: boolean | null;
  is_active?: boolean | null;
  last_service_at?: string | null;
  last_restock_at?: string | null;
  last_telemetry_at?: string | null;
  installed_at?: string | null;
  edge_mode?: string | null;
  connectivity_type?: string | null;
  id: number;
  created_at?: string | null;
  updated_at?: string | null;
}
export interface MachineUpdate {
  id?: number | null;
  serial_number?: string | null;
  machine_type?: string | null;
  name?: string | null;
  manufacturer?: string | null;
  model?: string | null;
  status?: string | null;
  operator_id?: number | null;
  location_id?: number | null;
  terminal_id?: string | null;
  pi_device_id?: string | null;
  sim_iccid?: string | null;
  firmware_version?: string | null;
  temperature?: number | null;
  is_online?: boolean | null;
  is_active?: boolean | null;
  last_service_at?: string | null;
  last_restock_at?: string | null;
  last_telemetry_at?: string | null;
  installed_at?: string | null;
  edge_mode?: string | null;
  connectivity_type?: string | null;
}
export interface MarketingTemplateCreate {
  name: string;
  category: string;
  template_type?: string | null;
  content_html?: string | null;
  thumbnail_url?: string | null;
  is_active?: boolean | null;
  id?: number | null;
}
export interface MarketingTemplateResponse {
  name: string;
  category: string;
  template_type?: string | null;
  content_html?: string | null;
  thumbnail_url?: string | null;
  is_active?: boolean | null;
  id: number;
  created_at?: string | null;
  updated_at?: string | null;
}
export interface MarketingTemplateUpdate {
  id?: number | null;
  name?: string | null;
  category?: string | null;
  template_type?: string | null;
  content_html?: string | null;
  thumbnail_url?: string | null;
  is_active?: boolean | null;
}
export interface OperatorCreate {
  name: string;
  contact_name?: string | null;
  contact_email?: string | null;
  contact_phone?: string | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  zip_code?: string | null;
  machine_count?: number | null;
  monthly_volume?: number | string | null;
  processing_rate?: number | string | null;
  software_rate?: number | string | null;
  is_active?: boolean | null;
  id?: number | null;
}
export interface OperatorResponse {
  name: string;
  contact_name?: string | null;
  contact_email?: string | null;
  contact_phone?: string | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  zip_code?: string | null;
  machine_count?: number | null;
  monthly_volume?: string | null;
  processing_rate?: string | null;
  software_rate?: string | null;
  is_active?: boolean | null;
  id: number;
  created_at?: string | null;
  updated_at?: string | null;
}
export interface OperatorUpdate {
  id?: number | null;
  name?: string | null;
  contact_name?: string | null;
  contact_email?: string | null;
  contact_phone?: string | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  zip_code?: string | null;
  machine_count?: number | null;
  monthly_volume?: number | string | null;
  processing_rate?: number | string | null;
  software_rate?: number | string | null;
  is_active?: boolean | null;
}
export interface OperatorWebsiteCreate {
  operator_id?: number | null;
  domain?: string | null;
  subdomain?: string | null;
  company_name: string;
  tagline?: string | null;
  logo_url?: string | null;
  primary_color?: string | null;
  phone?: string | null;
  email?: string | null;
  about_text?: string | null;
  services_json?: string | null;
  chatbot_enabled?: boolean | null;
  chatbot_greeting?: string | null;
  is_published?: boolean | null;
  template_id?: string | null;
  id?: number | null;
}
export interface OperatorWebsiteResponse {
  operator_id?: number | null;
  domain?: string | null;
  subdomain?: string | null;
  company_name: string;
  tagline?: string | null;
  logo_url?: string | null;
  primary_color?: string | null;
  phone?: string | null;
  email?: string | null;
  about_text?: string | null;
  services_json?: string | null;
  chatbot_enabled?: boolean | null;
  chatbot_greeting?: string | null;
  is_published?: boolean | null;
  template_id?: string | null;
  id: number;
  created_at?: string | null;
  updated_at?: string | null;
}
export interface OperatorWebsiteUpdate {
  id?: number | null;
  operator_id?: number | null;
  domain?: string | null;
  subdomain?: string | null;
  company_name?: string | null;
  tagline?: string | null;
  logo_url?: string | null;
  primary_color?: string | null;
  phone?: string | null;
  email?: string | null;
  about_text?: string | null;
  services_json?: string | null;
  chatbot_enabled?: boolean | null;
  chatbot_greeting?: string | null;
  is_published?: boolean | null;
  template_id?: string | null;
}
export interface ProductCreate {
  operator_id?: number | null;
  name: string;
  sku?: string | null;
  category?: string | null;
  unit_cost?: number | string | null;
  retail_price?: number | string | null;
  par_level?: number | null;
  image_url?: string | null;
  is_active?: boolean | null;
  id?: number | null;
}
export interface ProductResponse {
  operator_id?: number | null;
  name: string;
  sku?: string | null;
  category?: string | null;
  unit_cost?: string | null;
  retail_price?: string | null;
  par_level?: number | null;
  image_url?: string | null;
  is_active?: boolean | null;
  id: number;
  created_at?: string | null;
  updated_at?: string | null;
}
export interface ProductUpdate {
  id?: number | null;
  operator_id?: number | null;
  name?: string | null;
  sku?: string | null;
  category?: string | null;
  unit_cost?: number | string | null;
  retail_price?: number | string | null;
  par_level?: number | null;
  image_url?: string | null;
  is_active?: boolean | null;
}
export interface ProposalCreate {
  lead_id?: number | null;
  operator_id?: number | null;
  title: string;
  description?: string | null;
  machine_type?: string | null;
  machine_count?: number | null;
  monthly_revenue_estimate?: number | null;
  commission_split?: number | null;
  placement_fee?: number | null;
  contract_term_months?: number | null;
  status: string;
  sent_at?: string | null;
  viewed_at?: string | null;
  signed_at?: string | null;
  signature_data?: string | null;
  pdf_url?: string | null;
  id?: number | null;
}
export interface ProposalResponse {
  lead_id?: number | null;
  operator_id?: number | null;
  title: string;
  description?: string | null;
  machine_type?: string | null;
  machine_count?: number | null;
  monthly_revenue_estimate?: number | null;
  commission_split?: number | null;
  placement_fee?: number | null;
  contract_term_months?: number | null;
  status: string;
  sent_at?: string | null;
  viewed_at?: string | null;
  signed_at?: string | null;
  signature_data?: string | null;
  pdf_url?: string | null;
  id: number;
  created_at?: string | null;
  updated_at?: string | null;
}
export interface ProposalUpdate {
  id?: number | null;
  lead_id?: number | null;
  operator_id?: number | null;
  title?: string | null;
  description?: string | null;
  machine_type?: string | null;
  machine_count?: number | null;
  monthly_revenue_estimate?: number | null;
  commission_split?: number | null;
  placement_fee?: number | null;
  contract_term_months?: number | null;
  status?: string | null;
  sent_at?: string | null;
  viewed_at?: string | null;
  signed_at?: string | null;
  signature_data?: string | null;
  pdf_url?: string | null;
}
export interface RouteCreate {
  operator_id: number;
  driver_id?: number | null;
  name: string;
  status?: string | null;
  scheduled_date?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  machine_ids_json?: string | null;
  optimized_order_json?: string | null;
  total_distance_miles?: number | null;
  notes?: string | null;
  id?: number | null;
}
export interface RouteResponse {
  operator_id: number;
  driver_id?: number | null;
  name: string;
  status?: string | null;
  scheduled_date?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  machine_ids_json?: string | null;
  optimized_order_json?: string | null;
  total_distance_miles?: number | null;
  notes?: string | null;
  id: number;
  created_at?: string | null;
  updated_at?: string | null;
}
export interface RouteUpdate {
  id?: number | null;
  operator_id?: number | null;
  driver_id?: number | null;
  name?: string | null;
  status?: string | null;
  scheduled_date?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  machine_ids_json?: string | null;
  optimized_order_json?: string | null;
  total_distance_miles?: number | null;
  notes?: string | null;
}
export interface ServiceVisitCreate {
  machine_id: number;
  driver_id: number;
  route_id?: number | null;
  visit_type?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  notes?: string | null;
  cash_collected?: number | string | null;
  products_restocked_json?: string | null;
  issues_found_json?: string | null;
  id?: number | null;
}
export interface ServiceVisitResponse {
  machine_id: number;
  driver_id: number;
  route_id?: number | null;
  visit_type?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  notes?: string | null;
  cash_collected?: string | null;
  products_restocked_json?: string | null;
  issues_found_json?: string | null;
  id: number;
  created_at?: string | null;
}
export interface ServiceVisitUpdate {
  id?: number | null;
  machine_id?: number | null;
  driver_id?: number | null;
  route_id?: number | null;
  visit_type?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  notes?: string | null;
  cash_collected?: number | string | null;
  products_restocked_json?: string | null;
  issues_found_json?: string | null;
}
export interface TransactionCreate {
  machine_id: number;
  product_id?: number | null;
  amount: number | string;
  payment_method?: string | null;
  payment_status?: string | null;
  payment_ref?: string | null;
  card_brand?: string | null;
  card_last_four?: string | null;
  terminal_id?: string | null;
  slot_number?: number | null;
  id?: number | null;
}
export interface TransactionResponse {
  machine_id: number;
  product_id?: number | null;
  amount: string;
  payment_method?: string | null;
  payment_status?: string | null;
  payment_ref?: string | null;
  card_brand?: string | null;
  card_last_four?: string | null;
  terminal_id?: string | null;
  slot_number?: number | null;
  id: number;
  created_at?: string | null;
}
export interface TransactionUpdate {
  id?: number | null;
  machine_id?: number | null;
  product_id?: number | null;
  amount?: number | string | null;
  payment_method?: string | null;
  payment_status?: string | null;
  payment_ref?: string | null;
  card_brand?: string | null;
  card_last_four?: string | null;
  terminal_id?: string | null;
  slot_number?: number | null;
}
export interface UserResponse {
  email?: string | null;
  full_name?: string | null;
  is_active?: boolean;
  id: number;
  created_at?: string | null;
  updated_at?: string | null;
}
export interface UserUpdate {
  email?: string | null;
  full_name?: string | null;
  is_active?: boolean | null;
  password?: string | null;
}
export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
}
export interface auth__schemas__UserCreate {
  email: string;
  password: string;
}
export interface schemas__user__UserCreate {
  email: string;
  full_name?: string | null;
  is_active?: boolean;
  password: string;
}

// ── Bare-name entity aliases (response shapes) ──
export type Alert = AlertResponse;
export type Analytics = AnalyticsResponse;
export type DailyReport = DailyReportResponse;
export type EmailSendLog = EmailSendLogResponse;
export type EmailSequence = EmailSequenceResponse;
export type InventoryItem = InventoryItemResponse;
export type Lead = LeadResponse;
export type Location = LocationResponse;
export type Machine = MachineResponse;
export type MarketingTemplate = MarketingTemplateResponse;
export type Operator = OperatorResponse;
export type OperatorWebsite = OperatorWebsiteResponse;
export type Product = ProductResponse;
export type Proposal = ProposalResponse;
export type Route = RouteResponse;
export type ServiceVisit = ServiceVisitResponse;
export type Transaction = TransactionResponse;
export type User = UserResponse;
