// Auto-generated by FMPB v2.4.4 — named-export stub for @/components/ui/dialog
// Unauthored shadcn/ui compound component: permissive passthrough wrappers
// so named imports type-check and build (gig-agnostic fallback).
import * as React from 'react';

type StubProps = {
  children?: React.ReactNode;
  className?: string;
  [key: string]: unknown;
};

const _Stub = ({ children, className }: StubProps) => (
  <div className={className}>{children}</div>
);

export const Dialog = _Stub;
export const DialogContent = _Stub;
export const DialogHeader = _Stub;
export const DialogTitle = _Stub;
export const DialogTrigger = _Stub;

export default Dialog;
