// Auto-generated by FMPB v2.4.4 — named-export stub for @/components/ui/tabs
// Unauthored shadcn/ui compound component: permissive passthrough wrappers
// so named imports type-check and build (gig-agnostic fallback).
import * as React from 'react';

type StubProps = {
  children?: React.ReactNode;
  className?: string;
  [key: string]: unknown;
};

const _Stub = ({ children, className }: StubProps) => (
  <div className={className}>{children}</div>
);

export const Tabs = _Stub;
export const TabsContent = _Stub;
export const TabsList = _Stub;
export const TabsTrigger = _Stub;

export default Tabs;
