// JARVIS App — typed API client (CONTRACT-FIRST, generated)
// One function per backend operation. Wraps the locked Axios instance
// and unwraps `.data`. DO NOT EDIT BY HAND. Generated by frontend_codegen.py v1.33.0.

import { api } from './api';
import type {
  AlertCreate,
  AlertResponse,
  AlertUpdate,
  AnalyticsCreate,
  AnalyticsResponse,
  AnalyticsUpdate,
  Body_login_auth_login_post,
  Body_token_auth_token_post,
  Body_upload_task_file_uploads_tasks__task_id__upload_post,
  BulkPriceInventoryItemRequest,
  ChargeWholesaleAccountRequest,
  DailyReportCreate,
  DailyReportResponse,
  DailyReportUpdate,
  EmailSendLogCreate,
  EmailSendLogResponse,
  EmailSendLogUpdate,
  EmailSequenceCreate,
  EmailSequenceResponse,
  EmailSequenceUpdate,
  InventoryItemCreate,
  InventoryItemResponse,
  InventoryItemUpdate,
  LandownerCreate,
  LandownerPayoutCreate,
  LandownerPayoutResponse,
  LandownerPayoutUpdate,
  LandownerResponse,
  LandownerUpdate,
  LeadCreate,
  LeadResponse,
  LeadUpdate,
  LocationCreate,
  LocationResponse,
  LocationUpdate,
  MachineCreate,
  MachineResponse,
  MachineUpdate,
  MarketingTemplateCreate,
  MarketingTemplateResponse,
  MarketingTemplateUpdate,
  OperatorCreate,
  OperatorResponse,
  OperatorUpdate,
  OperatorWebsiteCreate,
  OperatorWebsiteResponse,
  OperatorWebsiteUpdate,
  ProductCreate,
  ProductResponse,
  ProductUpdate,
  ProposalCreate,
  ProposalResponse,
  ProposalUpdate,
  RevenueShareAgreementCreate,
  RevenueShareAgreementResponse,
  RevenueShareAgreementUpdate,
  RouteCreate,
  RouteResponse,
  RouteUpdate,
  ServiceVisitCreate,
  ServiceVisitResponse,
  ServiceVisitUpdate,
  StandingOrderCreate,
  StandingOrderResponse,
  StandingOrderUpdate,
  TelemetryMachineRequest,
  TransactionCreate,
  TransactionResponse,
  TransactionUpdate,
  UserCreate,
  UserResponse,
  WholesaleAccountCreate,
  WholesaleAccountResponse,
  WholesaleAccountUpdate,
  WholesaleOrderCreate,
  WholesaleOrderResponse,
  WholesaleOrderUpdate,
} from '@/types/api';

export async function list(): Promise<unknown> {
  const res = await api.get("/");
  return res.data;
}

export async function listAlerts(query?: { skip?: number; limit?: number }): Promise<AlertResponse[]> {
  const res = await api.get("/alerts/", { params: query });
  return res.data;
}

export async function createAlerts(body: AlertCreate): Promise<AlertResponse> {
  const res = await api.post("/alerts/", body);
  return res.data;
}

export async function getAlerts(alert_id: number): Promise<AlertResponse> {
  const res = await api.get(`/alerts/${alert_id}`);
  return res.data;
}

export async function updateAlerts(alert_id: number, body: AlertUpdate): Promise<AlertResponse> {
  const res = await api.put(`/alerts/${alert_id}`, body);
  return res.data;
}

export async function deleteAlerts(alert_id: number): Promise<void> {
  await api.delete(`/alerts/${alert_id}`);
}

export async function listAnalytics(query?: { skip?: number; limit?: number }): Promise<AnalyticsResponse[]> {
  const res = await api.get("/analytics/", { params: query });
  return res.data;
}

export async function createAnalytics(body: AnalyticsCreate): Promise<AnalyticsResponse> {
  const res = await api.post("/analytics/", body);
  return res.data;
}

export async function getAnalytics(analytics_id: number): Promise<AnalyticsResponse> {
  const res = await api.get(`/analytics/${analytics_id}`);
  return res.data;
}

export async function updateAnalytics(analytics_id: number, body: AnalyticsUpdate): Promise<AnalyticsResponse> {
  const res = await api.put(`/analytics/${analytics_id}`, body);
  return res.data;
}

export async function deleteAnalytics(analytics_id: number): Promise<void> {
  await api.delete(`/analytics/${analytics_id}`);
}

export async function createAuthLogin(body: Body_login_auth_login_post): Promise<unknown> {
  const res = await api.post("/auth/login", body);
  return res.data;
}

export async function listAuthMe(): Promise<unknown> {
  const res = await api.get("/auth/me");
  return res.data;
}

export async function createAuthRegister(body: UserCreate): Promise<unknown> {
  const res = await api.post("/auth/register", body);
  return res.data;
}

export async function createAuthToken(body: Body_token_auth_token_post): Promise<unknown> {
  const res = await api.post("/auth/token", body);
  return res.data;
}

export async function listDailyReports(query?: { skip?: number; limit?: number }): Promise<DailyReportResponse[]> {
  const res = await api.get("/daily_reports/", { params: query });
  return res.data;
}

export async function createDailyReports(body: DailyReportCreate): Promise<DailyReportResponse> {
  const res = await api.post("/daily_reports/", body);
  return res.data;
}

export async function getDailyReports(daily_report_id: number): Promise<DailyReportResponse> {
  const res = await api.get(`/daily_reports/${daily_report_id}`);
  return res.data;
}

export async function updateDailyReports(daily_report_id: number, body: DailyReportUpdate): Promise<DailyReportResponse> {
  const res = await api.put(`/daily_reports/${daily_report_id}`, body);
  return res.data;
}

export async function deleteDailyReports(daily_report_id: number): Promise<void> {
  await api.delete(`/daily_reports/${daily_report_id}`);
}

export async function listEmailSendLogs(query?: { skip?: number; limit?: number; lead_id?: number; sequence_id?: number }): Promise<EmailSendLogResponse[]> {
  const res = await api.get("/email_send_logs/", { params: query });
  return res.data;
}

export async function createEmailSendLogs(body: EmailSendLogCreate): Promise<EmailSendLogResponse> {
  const res = await api.post("/email_send_logs/", body);
  return res.data;
}

export async function getEmailSendLogs(email_send_log_id: number): Promise<EmailSendLogResponse> {
  const res = await api.get(`/email_send_logs/${email_send_log_id}`);
  return res.data;
}

export async function updateEmailSendLogs(email_send_log_id: number, body: EmailSendLogUpdate): Promise<EmailSendLogResponse> {
  const res = await api.put(`/email_send_logs/${email_send_log_id}`, body);
  return res.data;
}

export async function deleteEmailSendLogs(email_send_log_id: number): Promise<void> {
  await api.delete(`/email_send_logs/${email_send_log_id}`);
}

export async function listEmailSequences(query?: { skip?: number; limit?: number; operator_id?: number }): Promise<EmailSequenceResponse[]> {
  const res = await api.get("/email_sequences/", { params: query });
  return res.data;
}

export async function createEmailSequences(body: EmailSequenceCreate): Promise<EmailSequenceResponse> {
  const res = await api.post("/email_sequences/", body);
  return res.data;
}

export async function getEmailSequences(email_sequence_id: number): Promise<EmailSequenceResponse> {
  const res = await api.get(`/email_sequences/${email_sequence_id}`);
  return res.data;
}

export async function updateEmailSequences(email_sequence_id: number, body: EmailSequenceUpdate): Promise<EmailSequenceResponse> {
  const res = await api.put(`/email_sequences/${email_sequence_id}`, body);
  return res.data;
}

export async function deleteEmailSequences(email_sequence_id: number): Promise<void> {
  await api.delete(`/email_sequences/${email_sequence_id}`);
}

export async function createEmailSequencesActivate(email_sequence_id: number): Promise<EmailSequenceResponse> {
  const res = await api.post(`/email_sequences/${email_sequence_id}/activate`, undefined);
  return res.data;
}

export async function listHealth(): Promise<unknown> {
  const res = await api.get("/health");
  return res.data;
}

export async function listInventories(query?: { skip?: number; limit?: number }): Promise<InventoryItemResponse[]> {
  const res = await api.get("/inventories/", { params: query });
  return res.data;
}

export async function createInventories(body: InventoryItemCreate): Promise<InventoryItemResponse> {
  const res = await api.post("/inventories/", body);
  return res.data;
}

export async function createInventoriesBulkPrice(body: BulkPriceInventoryItemRequest): Promise<unknown> {
  const res = await api.post("/inventories/bulk_price", body);
  return res.data;
}

export async function getInventories(inventory_id: number): Promise<InventoryItemResponse> {
  const res = await api.get(`/inventories/${inventory_id}`);
  return res.data;
}

export async function updateInventories(inventory_id: number, body: InventoryItemUpdate): Promise<InventoryItemResponse> {
  const res = await api.put(`/inventories/${inventory_id}`, body);
  return res.data;
}

export async function deleteInventories(inventory_id: number): Promise<void> {
  await api.delete(`/inventories/${inventory_id}`);
}

export async function createInventoriesClearPrice(inventory_id: number): Promise<unknown> {
  const res = await api.post(`/inventories/${inventory_id}/clear_price`, undefined);
  return res.data;
}

export async function listLandownerPayouts(query?: { skip?: number; limit?: number; operator_id?: number; landowner_id?: number; agreement_id?: number }): Promise<LandownerPayoutResponse[]> {
  const res = await api.get("/landowner_payouts/", { params: query });
  return res.data;
}

export async function createLandownerPayouts(body: LandownerPayoutCreate): Promise<LandownerPayoutResponse> {
  const res = await api.post("/landowner_payouts/", body);
  return res.data;
}

export async function createLandownerPayoutsCalculate(): Promise<unknown> {
  const res = await api.post("/landowner_payouts/calculate", undefined);
  return res.data;
}

export async function getLandownerPayouts(landowner_payout_id: number): Promise<LandownerPayoutResponse> {
  const res = await api.get(`/landowner_payouts/${landowner_payout_id}`);
  return res.data;
}

export async function updateLandownerPayouts(landowner_payout_id: number, body: LandownerPayoutUpdate): Promise<LandownerPayoutResponse> {
  const res = await api.put(`/landowner_payouts/${landowner_payout_id}`, body);
  return res.data;
}

export async function deleteLandownerPayouts(landowner_payout_id: number): Promise<void> {
  await api.delete(`/landowner_payouts/${landowner_payout_id}`);
}

export async function createLandownerPayoutsPay(landowner_payout_id: number): Promise<LandownerPayoutResponse> {
  const res = await api.post(`/landowner_payouts/${landowner_payout_id}/pay`, undefined);
  return res.data;
}

export async function listLandowners(query?: { skip?: number; limit?: number; operator_id?: number }): Promise<LandownerResponse[]> {
  const res = await api.get("/landowners/", { params: query });
  return res.data;
}

export async function createLandowners(body: LandownerCreate): Promise<LandownerResponse> {
  const res = await api.post("/landowners/", body);
  return res.data;
}

export async function getLandowners(landowner_id: number): Promise<LandownerResponse> {
  const res = await api.get(`/landowners/${landowner_id}`);
  return res.data;
}

export async function updateLandowners(landowner_id: number, body: LandownerUpdate): Promise<LandownerResponse> {
  const res = await api.put(`/landowners/${landowner_id}`, body);
  return res.data;
}

export async function deleteLandowners(landowner_id: number): Promise<void> {
  await api.delete(`/landowners/${landowner_id}`);
}

export async function listLeads(query?: { skip?: number; limit?: number; operator_id?: number }): Promise<LeadResponse[]> {
  const res = await api.get("/leads/", { params: query });
  return res.data;
}

export async function createLeads(body: LeadCreate): Promise<LeadResponse> {
  const res = await api.post("/leads/", body);
  return res.data;
}

export async function getLeads(lead_id: number): Promise<LeadResponse> {
  const res = await api.get(`/leads/${lead_id}`);
  return res.data;
}

export async function updateLeads(lead_id: number, body: LeadUpdate): Promise<LeadResponse> {
  const res = await api.put(`/leads/${lead_id}`, body);
  return res.data;
}

export async function deleteLeads(lead_id: number): Promise<void> {
  await api.delete(`/leads/${lead_id}`);
}

export async function listLocations(query?: { skip?: number; limit?: number; operator_id?: number; landowner_id?: number }): Promise<LocationResponse[]> {
  const res = await api.get("/locations/", { params: query });
  return res.data;
}

export async function createLocations(body: LocationCreate): Promise<LocationResponse> {
  const res = await api.post("/locations/", body);
  return res.data;
}

export async function getLocations(location_id: number): Promise<LocationResponse> {
  const res = await api.get(`/locations/${location_id}`);
  return res.data;
}

export async function updateLocations(location_id: number, body: LocationUpdate): Promise<LocationResponse> {
  const res = await api.put(`/locations/${location_id}`, body);
  return res.data;
}

export async function deleteLocations(location_id: number): Promise<void> {
  await api.delete(`/locations/${location_id}`);
}

export async function listMachines(query?: { skip?: number; limit?: number; operator_id?: number; location_id?: number }): Promise<MachineResponse[]> {
  const res = await api.get("/machines/", { params: query });
  return res.data;
}

export async function createMachines(body: MachineCreate): Promise<MachineResponse> {
  const res = await api.post("/machines/", body);
  return res.data;
}

export async function getMachines(machine_id: number): Promise<MachineResponse> {
  const res = await api.get(`/machines/${machine_id}`);
  return res.data;
}

export async function updateMachines(machine_id: number, body: MachineUpdate): Promise<MachineResponse> {
  const res = await api.put(`/machines/${machine_id}`, body);
  return res.data;
}

export async function deleteMachines(machine_id: number): Promise<void> {
  await api.delete(`/machines/${machine_id}`);
}

export async function createMachinesTelemetry(machine_id: number, body: TelemetryMachineRequest): Promise<MachineResponse> {
  const res = await api.post(`/machines/${machine_id}/telemetry`, body);
  return res.data;
}

export async function listMarketingTemplates(query?: { skip?: number; limit?: number }): Promise<MarketingTemplateResponse[]> {
  const res = await api.get("/marketing_templates/", { params: query });
  return res.data;
}

export async function createMarketingTemplates(body: MarketingTemplateCreate): Promise<MarketingTemplateResponse> {
  const res = await api.post("/marketing_templates/", body);
  return res.data;
}

export async function getMarketingTemplates(marketing_template_id: number): Promise<MarketingTemplateResponse> {
  const res = await api.get(`/marketing_templates/${marketing_template_id}`);
  return res.data;
}

export async function updateMarketingTemplates(marketing_template_id: number, body: MarketingTemplateUpdate): Promise<MarketingTemplateResponse> {
  const res = await api.put(`/marketing_templates/${marketing_template_id}`, body);
  return res.data;
}

export async function deleteMarketingTemplates(marketing_template_id: number): Promise<void> {
  await api.delete(`/marketing_templates/${marketing_template_id}`);
}

export async function listOperatorWebsites(query?: { skip?: number; limit?: number; operator_id?: number }): Promise<OperatorWebsiteResponse[]> {
  const res = await api.get("/operator_websites/", { params: query });
  return res.data;
}

export async function createOperatorWebsites(body: OperatorWebsiteCreate): Promise<OperatorWebsiteResponse> {
  const res = await api.post("/operator_websites/", body);
  return res.data;
}

export async function getOperatorWebsites(operator_website_id: number): Promise<OperatorWebsiteResponse> {
  const res = await api.get(`/operator_websites/${operator_website_id}`);
  return res.data;
}

export async function updateOperatorWebsites(operator_website_id: number, body: OperatorWebsiteUpdate): Promise<OperatorWebsiteResponse> {
  const res = await api.put(`/operator_websites/${operator_website_id}`, body);
  return res.data;
}

export async function deleteOperatorWebsites(operator_website_id: number): Promise<void> {
  await api.delete(`/operator_websites/${operator_website_id}`);
}

export async function createOperatorWebsitesPublish(operator_website_id: number): Promise<OperatorWebsiteResponse> {
  const res = await api.post(`/operator_websites/${operator_website_id}/publish`, undefined);
  return res.data;
}

export async function listOperators(query?: { skip?: number; limit?: number }): Promise<OperatorResponse[]> {
  const res = await api.get("/operators/", { params: query });
  return res.data;
}

export async function createOperators(body: OperatorCreate): Promise<OperatorResponse> {
  const res = await api.post("/operators/", body);
  return res.data;
}

export async function getOperators(operator_id: number): Promise<OperatorResponse> {
  const res = await api.get(`/operators/${operator_id}`);
  return res.data;
}

export async function updateOperators(operator_id: number, body: OperatorUpdate): Promise<OperatorResponse> {
  const res = await api.put(`/operators/${operator_id}`, body);
  return res.data;
}

export async function deleteOperators(operator_id: number): Promise<void> {
  await api.delete(`/operators/${operator_id}`);
}

export async function listProducts(query?: { skip?: number; limit?: number; operator_id?: number }): Promise<ProductResponse[]> {
  const res = await api.get("/products/", { params: query });
  return res.data;
}

export async function createProducts(body: ProductCreate): Promise<ProductResponse> {
  const res = await api.post("/products/", body);
  return res.data;
}

export async function getProducts(product_id: number): Promise<ProductResponse> {
  const res = await api.get(`/products/${product_id}`);
  return res.data;
}

export async function updateProducts(product_id: number, body: ProductUpdate): Promise<ProductResponse> {
  const res = await api.put(`/products/${product_id}`, body);
  return res.data;
}

export async function deleteProducts(product_id: number): Promise<void> {
  await api.delete(`/products/${product_id}`);
}

export async function listProposals(query?: { skip?: number; limit?: number; lead_id?: number; operator_id?: number }): Promise<ProposalResponse[]> {
  const res = await api.get("/proposals/", { params: query });
  return res.data;
}

export async function createProposals(body: ProposalCreate): Promise<ProposalResponse> {
  const res = await api.post("/proposals/", body);
  return res.data;
}

export async function getProposals(proposal_id: number): Promise<ProposalResponse> {
  const res = await api.get(`/proposals/${proposal_id}`);
  return res.data;
}

export async function updateProposals(proposal_id: number, body: ProposalUpdate): Promise<ProposalResponse> {
  const res = await api.put(`/proposals/${proposal_id}`, body);
  return res.data;
}

export async function deleteProposals(proposal_id: number): Promise<void> {
  await api.delete(`/proposals/${proposal_id}`);
}

export interface ProposalEstimateBasis {
  source: string;
  machine_type: string | null;
  comparable_machines: number;
  machine_days_observed: number;
  window_days: number;
  avg_revenue_per_machine_day: string;
  machine_count: number;
  monthly_revenue_estimate: string;
  commission_split_pct: string | null;
  landowner_monthly_share: string | null;
}
export async function createProposalsEstimate(
  proposal_id: number,
): Promise<{ proposal: Record<string, unknown>; basis: ProposalEstimateBasis }> {
  const res = await api.post(`/proposals/${proposal_id}/estimate`);
  return res.data;
}
export async function createProposalsSend(proposal_id: number): Promise<ProposalResponse> {
  const res = await api.post(`/proposals/${proposal_id}/send`, undefined);
  return res.data;
}

export async function listReports(query?: { skip?: number; limit?: number }): Promise<Record<string, unknown>[]> {
  const res = await api.get("/reports/", { params: query });
  return res.data;
}

export async function listReportsSummary(): Promise<Record<string, unknown>> {
  const res = await api.get("/reports/summary");
  return res.data;
}

export async function listRevenueShareAgreements(query?: { skip?: number; limit?: number; operator_id?: number; landowner_id?: number; location_id?: number; machine_id?: number }): Promise<RevenueShareAgreementResponse[]> {
  const res = await api.get("/revenue_share_agreements/", { params: query });
  return res.data;
}

export async function createRevenueShareAgreements(body: RevenueShareAgreementCreate): Promise<RevenueShareAgreementResponse> {
  const res = await api.post("/revenue_share_agreements/", body);
  return res.data;
}

export async function getRevenueShareAgreements(revenue_share_agreement_id: number): Promise<RevenueShareAgreementResponse> {
  const res = await api.get(`/revenue_share_agreements/${revenue_share_agreement_id}`);
  return res.data;
}

export async function updateRevenueShareAgreements(revenue_share_agreement_id: number, body: RevenueShareAgreementUpdate): Promise<RevenueShareAgreementResponse> {
  const res = await api.put(`/revenue_share_agreements/${revenue_share_agreement_id}`, body);
  return res.data;
}

export async function deleteRevenueShareAgreements(revenue_share_agreement_id: number): Promise<void> {
  await api.delete(`/revenue_share_agreements/${revenue_share_agreement_id}`);
}

export async function listRoutes(query?: { skip?: number; limit?: number }): Promise<RouteResponse[]> {
  const res = await api.get("/routes/", { params: query });
  return res.data;
}

export async function createRoutes(body: RouteCreate): Promise<RouteResponse> {
  const res = await api.post("/routes/", body);
  return res.data;
}

export async function getRoutes(route_id: number): Promise<RouteResponse> {
  const res = await api.get(`/routes/${route_id}`);
  return res.data;
}

export async function updateRoutes(route_id: number, body: RouteUpdate): Promise<RouteResponse> {
  const res = await api.put(`/routes/${route_id}`, body);
  return res.data;
}

export async function deleteRoutes(route_id: number): Promise<void> {
  await api.delete(`/routes/${route_id}`);
}

export async function createRoutesOptimize(route_id: number): Promise<RouteResponse> {
  const res = await api.post(`/routes/${route_id}/optimize`, undefined);
  return res.data;
}

export async function listServiceVisits(query?: { skip?: number; limit?: number }): Promise<ServiceVisitResponse[]> {
  const res = await api.get("/service_visits/", { params: query });
  return res.data;
}

export async function createServiceVisits(body: ServiceVisitCreate): Promise<ServiceVisitResponse> {
  const res = await api.post("/service_visits/", body);
  return res.data;
}

export async function getServiceVisits(service_visit_id: number): Promise<ServiceVisitResponse> {
  const res = await api.get(`/service_visits/${service_visit_id}`);
  return res.data;
}

export async function updateServiceVisits(service_visit_id: number, body: ServiceVisitUpdate): Promise<ServiceVisitResponse> {
  const res = await api.put(`/service_visits/${service_visit_id}`, body);
  return res.data;
}

export async function deleteServiceVisits(service_visit_id: number): Promise<void> {
  await api.delete(`/service_visits/${service_visit_id}`);
}

export async function listStandingOrders(query?: { skip?: number; limit?: number; operator_id?: number; account_id?: number; machine_id?: number }): Promise<StandingOrderResponse[]> {
  const res = await api.get("/standing_orders/", { params: query });
  return res.data;
}

export async function createStandingOrders(body: StandingOrderCreate): Promise<StandingOrderResponse> {
  const res = await api.post("/standing_orders/", body);
  return res.data;
}

export async function createStandingOrdersRun(): Promise<unknown> {
  const res = await api.post("/standing_orders/run", undefined);
  return res.data;
}

export async function getStandingOrders(standing_order_id: number): Promise<StandingOrderResponse> {
  const res = await api.get(`/standing_orders/${standing_order_id}`);
  return res.data;
}

export async function updateStandingOrders(standing_order_id: number, body: StandingOrderUpdate): Promise<StandingOrderResponse> {
  const res = await api.put(`/standing_orders/${standing_order_id}`, body);
  return res.data;
}

export async function deleteStandingOrders(standing_order_id: number): Promise<void> {
  await api.delete(`/standing_orders/${standing_order_id}`);
}

export async function listTransactions(query?: { skip?: number; limit?: number }): Promise<TransactionResponse[]> {
  const res = await api.get("/transactions/", { params: query });
  return res.data;
}

export async function createTransactions(body: TransactionCreate): Promise<TransactionResponse> {
  const res = await api.post("/transactions/", body);
  return res.data;
}

export async function getTransactions(transaction_id: number): Promise<TransactionResponse> {
  const res = await api.get(`/transactions/${transaction_id}`);
  return res.data;
}

export async function updateTransactions(transaction_id: number, body: TransactionUpdate): Promise<TransactionResponse> {
  const res = await api.put(`/transactions/${transaction_id}`, body);
  return res.data;
}

export async function deleteTransactions(transaction_id: number): Promise<void> {
  await api.delete(`/transactions/${transaction_id}`);
}

export async function listUploads(query?: { skip?: number; limit?: number }): Promise<Record<string, unknown>[]> {
  const res = await api.get("/uploads/", { params: query });
  return res.data;
}

export async function createUploads(body: Record<string, unknown>): Promise<Record<string, unknown>> {
  const res = await api.post("/uploads/", body);
  return res.data;
}

export async function deleteUploadsTasksDelete(task_id: number, file_key: string): Promise<Record<string, unknown>> {
  const res = await api.delete(`/uploads/tasks/${task_id}/delete/${file_key}`);
  return res.data;
}

export async function getUploadsTasksDownload(task_id: number, file_key: string): Promise<unknown> {
  const res = await api.get(`/uploads/tasks/${task_id}/download/${file_key}`);
  return res.data;
}

export async function createUploadsTasksUpload(task_id: number, body: Body_upload_task_file_uploads_tasks__task_id__upload_post): Promise<string> {
  const res = await api.post(`/uploads/tasks/${task_id}/upload`, body);
  return res.data;
}

export async function getUploads(uploads_id: number): Promise<Record<string, unknown>> {
  const res = await api.get(`/uploads/${uploads_id}`);
  return res.data;
}

export async function updateUploads(uploads_id: number, body: Record<string, unknown>): Promise<Record<string, unknown>> {
  const res = await api.put(`/uploads/${uploads_id}`, body);
  return res.data;
}

export async function deleteUploads(uploads_id: number): Promise<Record<string, unknown>> {
  const res = await api.delete(`/uploads/${uploads_id}`);
  return res.data;
}

export async function listUsers(query?: { skip?: number; limit?: number }): Promise<UserResponse[]> {
  const res = await api.get("/users/", { params: query });
  return res.data;
}

export async function getUsers(user_id: number): Promise<UserResponse> {
  const res = await api.get(`/users/${user_id}`);
  return res.data;
}

export async function createWebhooksPrices(): Promise<unknown> {
  const res = await api.post("/webhooks/prices", undefined);
  return res.data;
}

export async function createWebhooksTransactions(): Promise<unknown> {
  const res = await api.post("/webhooks/transactions", undefined);
  return res.data;
}

export async function listWholesaleAccounts(query?: { skip?: number; limit?: number; operator_id?: number }): Promise<WholesaleAccountResponse[]> {
  const res = await api.get("/wholesale_accounts/", { params: query });
  return res.data;
}

export async function createWholesaleAccounts(body: WholesaleAccountCreate): Promise<WholesaleAccountResponse> {
  const res = await api.post("/wholesale_accounts/", body);
  return res.data;
}

export async function getWholesaleAccounts(wholesale_account_id: number): Promise<WholesaleAccountResponse> {
  const res = await api.get(`/wholesale_accounts/${wholesale_account_id}`);
  return res.data;
}

export async function updateWholesaleAccounts(wholesale_account_id: number, body: WholesaleAccountUpdate): Promise<WholesaleAccountResponse> {
  const res = await api.put(`/wholesale_accounts/${wholesale_account_id}`, body);
  return res.data;
}

export async function deleteWholesaleAccounts(wholesale_account_id: number): Promise<void> {
  await api.delete(`/wholesale_accounts/${wholesale_account_id}`);
}

export async function createWholesaleAccountsCharge(wholesale_account_id: number, body: ChargeWholesaleAccountRequest, headers?: { "Idempotency-Key"?: string }): Promise<WholesaleOrderResponse> {
  const res = await api.post(`/wholesale_accounts/${wholesale_account_id}/charge`, body, { headers });
  return res.data;
}

export async function listWholesaleOrders(query?: { skip?: number; limit?: number; operator_id?: number; account_id?: number; standing_order_id?: number; machine_id?: number; transaction_id?: number }): Promise<WholesaleOrderResponse[]> {
  const res = await api.get("/wholesale_orders/", { params: query });
  return res.data;
}

export async function createWholesaleOrders(body: WholesaleOrderCreate): Promise<WholesaleOrderResponse> {
  const res = await api.post("/wholesale_orders/", body);
  return res.data;
}

export async function getWholesaleOrders(wholesale_order_id: number): Promise<WholesaleOrderResponse> {
  const res = await api.get(`/wholesale_orders/${wholesale_order_id}`);
  return res.data;
}

export async function updateWholesaleOrders(wholesale_order_id: number, body: WholesaleOrderUpdate): Promise<WholesaleOrderResponse> {
  const res = await api.put(`/wholesale_orders/${wholesale_order_id}`, body);
  return res.data;
}

export async function deleteWholesaleOrders(wholesale_order_id: number): Promise<void> {
  await api.delete(`/wholesale_orders/${wholesale_order_id}`);
}

export async function listWsStatus(): Promise<unknown> {
  const res = await api.get("/ws/status");
  return res.data;
}
